title: Saptarshi Sinha
logo: ![alt text](https://github.com/SinhaSaptarshi/sinhasaptarshi.github.io/blob/master/DSC_5798%20.jpg?raw=true)
theme: jekyll-theme-cayman
description: Homepage of Saptarshi
